import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Nav from './components/common/Nav';
import QueryProvider from './components/QueryProvider';

const interRegular = localFont({
  src: './fonts/InterRegular.woff',
  variable: '--font-inter-regular',
  weight: '400',
});
const poppinsBold = localFont({
  src: './fonts/PoppinsBold.woff',
  variable: '--font-poppins-bold',
  weight: '600',
});

const poppinsRegular = localFont({
  src: './fonts/PoppinsRegular.woff',
  variable: '--font-poppins',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interRegular.variable} ${poppinsBold.variable} ${poppinsRegular.variable} antialiased text-primary`}
      >
        <Nav />
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
